#!/system/bin/sh

VOLTAGE=-20mV

/system/bin/insmod /system/lib/modules/bacem_tweak.ko
/system/bin/insmod /system/lib/modules/cpufreq_interactive.ko

OLDGOV=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 312000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 832000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo $OLDGOV > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo $VOLTAGE > /proc/sys/bacem/volt/cpu
