#!/system/bin/sh
# DarkyROM 2011
# Much faster zipalign.

# Changelog:
# 1.3 (5/8/12) new log system. system remount deleted (by: kurotsugi)
# 1.2 (17/1/11) Added /data/zipalign.db file for faster apk check (ninpo,Bo$s)
# 1.1 (12/1/09) Switched to zipalign -c 4 to check the apk instead of MD5 (oknowton)
# 1.0 (11/30/09) Original

LOG_FILE=/data/kuro_zalign.log
ZIPALIGNDB=/data/kuro_zalign.db

if [ -e $LOG_FILE ]; then
	rm $LOG_FILE;
fi;

if [ ! -f $ZIPALIGNDB ]; then
	touch $ZIPALIGNDB;
fi;

# the preface
echo "==========================
# TWEAK KURO-ZALIGN FILE #
==========================
in the name of Allah, 
the most beneficent, 
the most mercifull
==========================
system information:
vendor   : $( getprop ro.product.brand )
model    : $( getprop ro.product.model ) 
ROM      : $( getprop ro.build.display.id )

running the script...
start at: 
$( date +"%m-%d-%Y %H:%M:%S" )
==========================" | tee -a $LOG_FILE;

# zipalign script (not modified) 
for DIR in /system/app /data/app ; do
  cd $DIR
  for APK in *.apk ; do
    if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ] ; then
      echo "zipaligned: $DIR/$APK" | tee -a $LOG_FILE
    else
      zipalign -c 4 $APK
      if [ $? -eq 0 ] ; then
        echo "now zipaligned: $DIR/$APK" | tee -a $LOG_FILE
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
      else
        echo "Now aligning: $DIR/$APK" | tee -a $LOG_FILE
        zipalign -f 4 $APK /cache/$APK
        busybox mount -o rw,remount /system
        cp -f -p /cache/$APK $APK
        busybox rm -f /cache/$APK
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
      fi
    fi
  done
done

touch $ZIPALIGNDB

# end
echo "==========================
done at: 
$( date +"%m-%d-%Y %H:%M:%S" )
all praise is due to Allah
==========================
--   have a nice day    -- 
      kurotsugi@xda
==========================" | tee -a $LOG_FILE;

